version: "3"

services:
  log:
    env_file: environment.env
    build:
      context: .
      dockerfile: ./docker/log/Dockerfile

  build-deps:
    env_file: environment.env
    build:
      context: .
      dockerfile: ./docker/deps/Dockerfile
    volumes:
      - ./vendor:/opt/ext_vendor
    command: /opt/copy_deps.sh

  dev-server:
    env_file: environment.env
    environment:
      - CONSOLE_LOGS=0
    build:
      context: .
      args:
        # Remember to keep this consistent
        - django_secret_key=secret_key!
    command: ./start_dev_server.sh
    ports:
      - "8000:80"
    volumes:
      - ./src:/opt/code
    depends_on:
      - log

  test:
    env_file: environment.env
    environment:
      - CONSOLE_LOGS=1
    build:
      context: .
      args:
        # Remember to keep this consistent
        - django_secret_key=secret_key!
    entrypoint: pytest
    volumes:
      - ./src:/opt/code
    depends_on:
      - build-deps

  # Producion related
  server:
    image: energyaustralia-coding-test
    env_file: environment.env
    build:
      context: .
      args:
        # Remember to keep this consistent
        - django_secret_key=secret_key!
    command: /opt/server/start_server.sh
    ports:
      - "8080:80"
    depends_on:
      - log
